name: Notion同步到Hugo

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时自动同步
  workflow_dispatch:  # 允许手动触发

# 添加权限设置
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # 2. 从Notion同步文章
      - name: Notion to Markdown
        uses: yucchiy/notion-to-markdown@v0.3.2
        with:
          notion_auth_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          output_directory_path_template: 'content/posts/{{slug}}.md'
          
      # 3. 安装Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 4. 构建网站
      - name: Build
        run: hugo --minify

      # 5. 提交更改
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Sync from Notion $(date +'%Y-%m-%d %H:%M:%S')"
          
      # 6. 推送到GitHub
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # 7. 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
